[package]
name = "scp-metatitle-checker"
version = "0.1.0"
authors = ["Pioppoido <riced1999r@gmail.com>"]
edition = "2018"

[dependencies]
scraper = "0.12.0"
reqwest = { version = "0.11.0", features=["blocking"] }
